### ISSUE TITLE
dLeynaBackend D-Bus Error: "To make asynchronous calls, receive signals or export objects[...]"

### ISSUE THREAD

**Issue by JayFoxRox** [tkem/mopidy-dleyna#41] opened 2016-03-07 16:08 UTC
Hi,

Arch Linux on RPi (512MB).
Installed Mopidy-dLeyna using pip2, installed dleyna-server and python2-dbus using pacman.
Mopidy started using systemd service.
Mopidy-dLeyna keeps getting errors and won't work.

Here is my log:

```
Mar 07 08:55:45 raspberrypi mopidy[189]: INFO     Starting Mopidy backends: dLeynaBackend, YouTubeBackend, M3UBackend, FileBackend
Mar 07 08:55:45 raspberrypi mopidy[189]: INFO     Starting Mopidy-dLeyna D-Bus daemon
Mar 07 08:55:46 raspberrypi mopidy[189]: INFO     Audio output set to "autoaudiosink"
Mar 07 08:55:46 raspberrypi mopidy[189]: ERROR    Error starting Mopidy-dLeyna: To make asynchronous calls, receive signals or export objects, D-Bus connections must be
 attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
Mar 07 08:55:46 raspberrypi mopidy[189]: ERROR    Got un-handled exception from dLeynaBackend
Mar 07 08:55:46 raspberrypi mopidy[189]: Traceback (most recent call last):
Mar 07 08:55:46 raspberrypi mopidy[189]:   File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 237, in _actor_error_handling
Mar 07 08:55:46 raspberrypi mopidy[189]:     yield
Mar 07 08:55:46 raspberrypi mopidy[189]:   File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 385, in start_backends
Mar 07 08:55:46 raspberrypi mopidy[189]:     config=config, audio=audio).proxy()
Mar 07 08:55:46 raspberrypi mopidy[189]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 93, in start
Mar 07 08:55:46 raspberrypi mopidy[189]:     obj = cls(*args, **kwargs)
Mar 07 08:55:46 raspberrypi mopidy[189]:   File "/usr/lib/python2.7/site-packages/mopidy_dleyna/backend.py", line 42, in __init__
Mar 07 08:55:46 raspberrypi mopidy[189]:     raise exceptions.ExtensionError('Error starting dLeyna client')
Mar 07 08:55:46 raspberrypi mopidy[189]: ExtensionError: Error starting dLeyna client
```

**Comment by tkem** [comment] 2016-03-07 16:57
Could you give dleyna-server and python2-dbus versions, please.

**Comment by JayFoxRox** [comment] 2016-03-07 17:50
community/mopidy 2.0.0-2 [installed]
extra/dleyna-connector-dbus 0.2.0-2 [installed]
extra/dleyna-core 0.5.0-1 [installed]
extra/dleyna-server 0.5.0-1 [installed]
extra/python-dbus-common 1.2.2-1 [installed]
extra/python2-dbus 1.2.2-1 [installed]

and using "pip2 list":

...
Mopidy (2.0.0)
Mopidy-dLeyna (1.0.5)
Mopidy-MusicBox-Webclient (2.2.0)
Mopidy-Youtube (2.0.2)
...

It's the most recent available for my Arch Linux on RPi. I did a system upgrade just before installing mopidy (and mopidy-dleyna) yesterday.

**Comment by tkem** [comment] 2016-03-07 18:27
Both Debian Jessie and Ubuntu 14.04LTS seem to have python-dbus 1.2.0; they also have dleyna-server 0.4.0, but this shouldn't be the issue here (though dleyna 0.5.0 is completely untested and may bring its own share of of incompatibilities). I'll look into that, but since I don't run Arch, this may take some time...

**Comment by tkem** [comment] 2016-04-08 17:08
Sorry it took me so long... Any news on this? I upgraded to dbus-python 1.2.4, but could not reproduce your error.

As for the error message, Mopidy-dLeyna _does_ explicitly set a `mainloop` in https://github.com/tkem/mopidy-dleyna/blob/master/mopidy_dleyna/client.py#L153, so I'm kind of lost here...

EDIT: Ah, looks like it doesn't, really. Sorry, will look further into this!

**Comment by tkem** [comment] 2016-04-08 17:20
@JayFoxRox: Could you please run 

```
python -m mopidy_dleyna.client
```

and see if it produces a similar error message?

**Comment by JayFoxRox** [comment] 2016-04-08 17:42
I've fixed this differently and I don't remember how. I'll still try to reproduce the bug for you (and find my workaround) so we can keep the issue alive. I'll probably get to it on the next couple of days. In case I'm not back sometime next week you can feel free to close this

**Comment by tkem** [comment] 2016-04-08 18:34
Great to hear it's working for you now!
Take your time, this issue's been open for so long now, a few extra days (or weeks) won't matter...

**Comment by tkem** [comment] 2016-05-19 19:51
@JayFoxRox: Closing this for now. Feel free to reopen/comment if you can provide more details.

**Comment by wahoonie76** [comment] 2016-08-07 13:55
Hi tkem,

got the same error like JayFoxRox on my Raspi B+ with newest Arch installed.

journalctl says: 

```
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]: INFO     Starting Mopidy-dLeyna D-Bus daemon
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]: ERROR    Error starting Mopidy-dLeyna: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]: INFO     Audio output set to "autoaudiosink"
Aug 07 15:23:52 RaspMPDLivingroommopidy[4937]: ERROR    Got un-handled exception from dLeynaBackend
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]: Traceback (most recent call last):
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:   File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 237, in _actor_error_handling
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:     yield
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:   File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 385, in start_backends
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:     config=config, audio=audio).proxy()
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 94, in start
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:     obj = cls(*args, **kwargs)
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:   File "/usr/lib/python2.7/site-packages/mopidy_dleyna/backend.py", line 42, in __init__
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]:     raise exceptions.ExtensionError('Error starting dLeyna client')
Aug 07 15:23:52 RaspMPDLivingroom mopidy[4937]: ExtensionError: Error starting dLeyna client
```

and when I start "python2 -m mopidy_dleyna.client" on terminal:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
     exec code in run_globals
File "/usr/lib/python2.7/site-packages/mopidy_dleyna/client.py", line 236, in <module>
      import dbus.mainloop.glib
File "/usr/lib/python2.7/site-packages/dbus/mainloop/glib.py", line 29, in <module>
      from _dbus_glib_bindings import DBusGMainLoop, gthreads_init
ImportError: libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
```

I think the system is up to date (did pacman -Syu...)

thanks for your help

**Comment by tkem** [comment] 2016-08-07 15:17
Well, unless @JayFoxRox can remember how he fixed this issue, there's not much I can do, I'm afraid.
However, searching for the `ImportError` message hints at `dbus-glib` not being installed:
https://bbs.archlinux.org/viewtopic.php?id=141581

**Comment by tkem** [comment] 2016-08-07 16:04
In Debian, this is a dependency of the `python-dbus` package: https://packages.debian.org/de/sid/python-dbus
I don't know about Arch, though.

**Comment by wahoonie76** [comment] 2016-08-07 16:58
Installing     dbus-glib   with     pacman -S dbus-glib    seems to work.

Thanks for your help!

**Comment by tkem** [comment] 2016-08-07 17:02
No big deal. Might add to installation instructions, as well.

**Comment by tkem** [comment] 2016-08-07 17:04
Add side/footnote about installing `dbus-glib` on Arch (and potentially other dists).

**Closed as completed** 2016-09-23 16:19 UTC
Labels: question
