### ISSUE TITLE
search results does not respect search limit

### ISSUE THREAD

**Issue by mczerski** [tkem/mopidy-dleyna#64] opened 2018-06-09 22:22 UTC
https://github.com/tkem/mopidy-dleyna/blob/9798b535f13d7e3762cf4db5f17b2d1fcedc17a2/mopidy_dleyna/client.py#L201

I think there is a problem in search. The total variable represents all items matching the query, so the search will return all the items regardless of the limit set in the config file. If this is the expected behaviour then this makes problems for queries that results in large number of items - what makes mopidy timeout.

**Comment by tkem** [comment] 2018-06-10 14:33
It is the intended behavior, as per http://mopidy-dleyna.readthedocs.io/en/latest/config.html#confval-dleyna/upnp_search_limit:

> The maximum number of objects to retrieve per UPnP Search action

If more than `upnp_search_limit` objects are to be retrieved, multiple requests will be issued; this has shown to be considerably faster than retrieving all items in one request (if the DLNA server even supports this, some set arbitrary limits on the number of objects returned).

**Comment by mczerski** [comment] 2018-06-10 15:06
ok, thanks for clarifying. But still there is a problem with queries that can return large numbers of items, which cause mopidy to timeout (don't know where the timeout happens, it maybe in the frontend - I use mopidy-iris). Other mopidy plugins like spotify or youtube provide settings for maximum number of items to return in a single search. This makes sense because there is no need to display a lot of results in the gui and it makes search queries last longer. Probably it should be handled by the core functionality by providing some sort of API but it is not and all the backend plugins must handle this by themselves. If You think this is not an issue You may close this issue :)

**Comment by tkem** [comment] 2018-06-10 15:18
Well, I *do* think it's an issue, but alas one I don't have a proper solution for ;-)
First of all, there's no such thing as a "Mopidy timeout" - IIRC Mopidy (the server) will wait indefinitely on every backend to fulfill a request - any timeouts you may see are generated by the client (and may be configurable there).
IMHO, the proper "solution" would be for the Mopidy API to provide *pagination*, i.e. allow clients to pass `limit` and `offset` parameters with search and other commands. That way, the client would control how many objects are retrieved, and could "split up" large queries into smaller parts and remain responsive.
This has been on the agenda for quite a while (just search Mopidy's open issues), but there hasn't been any progress on it AFAIK.
So, yes, I think it *is* an issue, but none that mopidy-dleyna can solve properly, I think.
Therefore I'm closing this, as you suggested ;-)

**Closed as completed by tkem** 2018-06-10 15:18 UTC
